[phases.setup]
nixPkgs = [
    'nodejs_18',
    'pnpm-8_x',
]

[phases.install]
cmds = ['pnpm i --frozen-lockfile']

[phases.build]
cmds = ['pnpm -F backend build']

[start]
cmd = 'pnpm -F backend start'
